### ISSUE TITLE
Getting Nonce verification failed error message when activating addons

### ISSUE THREAD

**Issue by idomskt** [wp-erp/wp-erp#1389]
Hello,

I installed the WP ERP plugin on my website, which works well.

However, after activating an add-on (such as hr frontend), my website crashes, and I get the 'Nonce verification failed' message.

At first, I thought that the problem was with that add-on, but after activating the Inventory add-on, I got the same error.

I suspect now that the problem is with the core plugin.

Please test and advise.

Thank you

**Comment by RatulHasan** [comment]
> Hello,
> 
> I installed the WP ERP plugin on my website, which works well.
> 
> However, after activating an add-on (such as hr frontend), my website crashes, and I get the 'Nonce verification failed' message.
> 
> At first, I thought that the problem was with that add-on, but after activating the Inventory add-on, I got the same error.
> 
> I suspect now that the problem is with the core plugin.
> 
> Please test and advise.
> 
> Thank you

Hello @idomskt ,
Can you please go to WP ERP > Tools > Status? Then click `Get system report` and copy the information and paste it here for more specifics.

Thank you.

**Comment by sycshk** [comment]
Has this been solved?  I believe this error might be related.
 This plugin failed to load properly and is paused during recovery mode.
An error of type E_ERROR was caused in line 44 of the file /var/www/wordpress/wp-content/plugins/erp/includes/API/ApiRegistrar.php. Error message: Uncaught Error: Class "WeDevs\Attendance\Api\AttendanceController" not found in /var/www/wordpress/wp-content/plugins/erp/includes/API/ApiRegistrar.php:44 Stack trace: #0 /var/www/wordpress/wp-includes/class-wp-hook.php(324): WeDevs\ERP\API\ApiRegistrar->register_rest_routes() #1 /var/www/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /var/www/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /var/www/wordpress/wp-includes/rest-api.php(628): do_action() #4 /var/www/wordpress/wp-includes/rest-api.php(452): rest_get_server() #5 /var/www/wordpress/wp-includes/class-wp-hook.php(324): rest_api_loaded() #6 /var/www/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #7 /var/www/wordpress/wp-includes/plugin.php(565): WP_Hook->do_action() #8 /var/www/wordpress/wp-includes/class-wp.php(418): do_action_ref_array() #9 /var/www/wordpress/wp-includes/class-wp.php(818): WP->parse_request() #10 /var/www/wordpress/wp-includes/functions.php(1342): WP->main() #11 /var/www/wordpress/wp-blog-header.php(16): wp() #12 /var/www/wordpress/index.php(17): require('...') #13 {main} thrown

**Comment by iftakharul-islam** [comment]
@sycshk, can you please create a new issue regarding this? It's not related to the problem you've mentioned. 
Please share more details on how we can recreate the same issue you've found in WP ERP.
