### ISSUE TITLE
Unable to void payment entry in sales tab

### ISSUE THREAD

**Issue by mehroz1** [wp-erp/wp-erp#658]
I am unable to void payment entry in sales tab:
![wp-erp-bug](https://user-images.githubusercontent.com/9348863/40531613-4a9c8cae-6016-11e8-8efb-75ce5189053a.jpg)

```
debug.log result:

[25-May-2018 07:08:24 UTC] PHP Notice:  Object of class Illuminate\Support\Collection could not be converted to int in C:\wamp64\www\dummy\wp-content\plugins\erp\modules\accounting\includes\functions-transaction.php on line 196

[25-May-2018 07:08:24 UTC] PHP Stack trace:

[25-May-2018 07:08:24 UTC] PHP   1. {main}() C:\wamp64\www\dummy\wp-admin\admin-ajax.php:0

[25-May-2018 07:08:24 UTC] PHP   2. do_action() C:\wamp64\www\dummy\wp-admin\admin-ajax.php:91

[25-May-2018 07:08:24 UTC] PHP   3. WP_Hook->do_action() C:\wamp64\www\dummy\wp-includes\plugin.php:453

[25-May-2018 07:08:24 UTC] PHP   4. WP_Hook->apply_filters() C:\wamp64\www\dummy\wp-includes\class-wp-hook.php:323

[25-May-2018 07:08:24 UTC] PHP   5. WeDevs\ERP\Accounting\Ajax_Handler->transaction_row_bulk_action() C:\wamp64\www\dummy\wp-includes\class-wp-hook.php:298

[25-May-2018 07:08:24 UTC] PHP   6. erp_ac_update_transaction_to_void() C:\wamp64\www\dummy\wp-content\plugins\erp\modules\accounting\includes\class-ajax.php:190

[25-May-2018 07:08:24 UTC] PHP   7. erp_ac_get_transaction() C:\wamp64\www\dummy\wp-content\plugins\erp\modules\accounting\includes\functions-transaction.php:1249

[25-May-2018 07:08:24 UTC] PHP   8. intval() C:\wamp64\www\dummy\wp-content\plugins\erp\modules\accounting\includes\functions-transaction.php:196

[25-May-2018 07:08:24 UTC] PHP Fatal error:  Uncaught BadMethodCallException: Method update does not exist. in C:\wamp64\www\dummy\wp-content\plugins\erp\vendor\illuminate\support\Traits\Macroable.php:74
Stack trace:
#0 C:\wamp64\www\dummy\wp-content\plugins\erp\modules\accounting\includes\functions-transaction.php(1125): Illuminate\Support\Collection->__call('update', Array)
#1 C:\wamp64\www\dummy\wp-content\plugins\erp\modules\accounting\includes\functions-transaction.php(1259): erp_ac_update_transaction(Object(Illuminate\Support\Collection), Array)
#2 C:\wamp64\www\dummy\wp-content\plugins\erp\modules\accounting\includes\class-ajax.php(190): erp_ac_update_transaction_to_void('12', Array)
#3 C:\wamp64\www\dummy\wp-includes\class-wp-hook.php(298): WeDevs\ERP\Accounting\Ajax_Handler->transaction_row_bulk_action('')
#4 C:\wamp64\www\dummy\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#5 C:\wamp64\www\dummy\wp-includes\plugin.php(453): WP_Hook->do_action(Array)
#6 C:\wamp64\www\dummy\wp-admin\admin-ajax.php(91): do_action('wp_ajax_ in C:\wamp64\www\dummy\wp-content\plugins\erp\vendor\illuminate\support\Traits\Macroable.php on line 74
```

**Comment by mehroz1** [comment]
Please also note that second line turned to  0 when i pressed pay button

**Comment by shawon786** [comment]
Thanks for reporting the bug.
We are working on it.

Regards :)
